### ISSUE TITLE
Error: (1) Class not registered -> file: classfactoryfar.cpp line: 36

### ISSUE THREAD

**Issue by margarett** [Uzuul23/NKOpcTunnel#1]
Hi @Uzuul23 

I am testing your software and got into an issue:
When the Client tries to "Check" the newly created tunnel, it returns a "Class not registered" error. On the Server log, the following can be found:

2024-03-28 15:17:02.819 [1540:3416] Message: COPCFarSrv -- client[3] ssl connected from : 192.168.10.123/55864
2024-03-28 15:17:02.820 [1540:1848] Message: COPCFarSrv -- client[3] disconnected
2024-03-28 15:17:02.844 [1540:3416] Message: COPCFarSrv -- client[4] ssl connected from : 192.168.10.123/55865
2024-03-28 15:17:02.845 [1540:164] Error: (1) Class not registered -> file: classfactoryfar.cpp line: 36
2024-03-28 15:17:10.643 [1540:164] Error: (7) connection closed -> file: sslsocket.cpp line: 133
2024-03-28 15:17:10.643 [1540:3660] Message: COPCFarSrv -- client[4] disconnected

Any idea?
The server is a Windows Embedded Standard (Win7 SP1 based) and I installed the required Microsoft Visual C++ Redistributable 2013/2017 packages.
The client is W10.

**Comment by Uzuul23** [comment]
Hi @margarett 

the error is from here:

src/cpp/com/classfactoryfar.cpp

namespace NkCom
{
	CClassFactoryFar::CClassFactoryFar(CServer* pSrv, REFCLSID rclsid, DWORD dwClsContext, REFIID riid)
		: CComFarUnknown(pSrv)
	{
		**HRESULT hr = CoGetClassObject(rclsid, dwClsContext, 0, riid, (void**)&m_spUnknown);**
		NkError::CBaseException::check_result(hr, __FILE__, __LINE__);
		NkError::CBaseException::check_result(query_interface(riid), __FILE__, __LINE__);
	}

....

please check this:

https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-cogetclassobject

uzuul23

**Comment by margarett** [comment]
Hi @Uzuul23 
Thank you for your reply.
I had no idea what to do with that information :-) but just to let you know I found the problem (and it's not related to that)

At the client side config I was just adding the IP of the server. As it makes sense (now it does) we have to push the "three dots button" (to the right of the "Globally Unique Identifier") and select which OPC instance we want to connect to. The server-side available servers are shown, we select the one we want and after that it "Verifies" and connects without issues.

Your Tunneller works great!
